INSERT INTO PLAYERS(ID, NAME , LASTNAME, POSITION, AGE, EXPERIENCE, SCORED_POINTS, LOST_POINTS ) VALUES(01, 'Dragana Pekić', 'Setter', 24, 11, 43, 19);
INSERT INTO PLAYERS(ID, NAME , LASTNAME, POSITION, AGE, EXPERIENCE, SCORED_POINTS, LOST_POINTS ) VALUES(02, 'Ivana Igić', 'Opposite', 28, 16, 112, 41);
INSERT INTO PLAYERS(ID, NAME , LASTNAME, POSITION, AGE, EXPERIENCE, SCORED_POINTS, LOST_POINTS ) VALUES(03, 'Marija Vuković', 'Attacker', 23, 12, 58, 28);
INSERT INTO PLAYERS(ID, NAME , LASTNAME, POSITION, AGE, EXPERIENCE, SCORED_POINTS, LOST_POINTS ) VALUES(05, 'Milica Ivković', 'Receiver', 27, 18, 63, 22);
INSERT INTO PLAYERS(ID, NAME , LASTNAME, POSITION, AGE, EXPERIENCE, SCORED_POINTS, LOST_POINTS ) VALUES(06, 'Tijana Davidović', 'Outside Hitter', 31, 22, 129, 32);
INSERT INTO PLAYERS(ID, NAME , LASTNAME, POSITION, AGE, EXPERIENCE, SCORED_POINTS, LOST_POINTS ) VALUES(07, 'Matea Jovović', 'Setter', 20, 11, 27, 8);
INSERT INTO PLAYERS(ID, NAME , LASTNAME, POSITION, AGE, EXPERIENCE, SCORED_POINTS, LOST_POINTS ) VALUES(08, 'Anđelina Marković', 'Libero', 26, 16, 26, 13);